name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        id: install-deps-ubuntu
        run: |
          sudo apt-get install -y clang-format

      - name: Lint
        run: |
          clang-format --dry-run -Werror *.c
